compute_environment: LOCAL_MACHINE
distributed_type: 'MULTI_GPU'
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: 'no'
num_machines: 2
num_processes: 1
rdzv_backend: static
use_cpu: false
